### ISSUE TITLE
In install.sh, use "echo ~~ >> " instead of "echo ~~ | cat >> "

### ISSUE THREAD

**Issue by taeguk** [JimJeon/devenv#1]
https://github.com/JimJeon/devenv/commit/3044735b1403681fe914d958263c5733f8939fd7

How about use "echo ~~ >> " instead of "echo ~~ | cat >> ".
I think that cat is not neccessary.

**Comment by JimJeon** [comment]
thanks for advice :)

**Comment by taeguk** [comment]
Still so many similar codes in install.sh!

**Comment by JimJeon** [comment]
yes I'm aware of that. I will fix them soon.

**Comment by JimJeon** [comment]
done!

**Comment by JimJeon** [comment]
done?

**Comment by taeguk** [comment]
I done know ㅋㅋㅋ
